### ISSUE TITLE
Avatar and Photo Updates to 'About Page'

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#12]
here are the list of updates needed for the 'About Page' --'Who we are' 

- [ ] add photos, avatars and silhouettes next to Staff and Advisory Committee

**Comment by levjoy** [comment]
Waiting on all of the images, Okthanks is compiling.

**Comment by levjoy** [comment]
So far here's the tally: 

- Nathan: waiting 
- Sara: no response
- Matt: no response 
- Harlo: no response 
- Holly: have photo 
- Matt: have photo
- Soraya: silhouette
- Bruce: have photo
- Jamie: waiting
- Ethan: have photo

**Comment by tiffrobo** [comment]
Here's the updated 'Who we are' section.

- [ ] We need to add Tiffany's name, title, bio, avatar, email and PGP key under the 'Staff' section.

[Who-We-Are.pdf](https://github.com/digital-security-exchange/exchange-new/files/2307322/Who-We-Are.pdf)

- [ ] @levjoy can you add my PGP key and hyperlink my email, please?

@redaranj here are the avatars, photos and silhouettes in a compressed file if needed. Should be as followed:

- Tiffany: avatar 
- Nathan: photo
- Sara: silhouette
- Matt: silhouette
- Harlo: silhouette
- Holly: avatar
- Matt: photo
- Soraya: silhouette
- Bruce: photo
- Jamie: photo
- Ethan: photo

[Website-About-Images.zip](https://github.com/digital-security-exchange/exchange-new/files/2307345/Website-About-Images.zip)

**Comment by levjoy** [comment]
Tiffany's bio and PGP are added, up to date in develop.

**Comment by tiffrobo** [comment]
looks good! closing the ticket
