### ISSUE TITLE
Keep buttons ('Get Help' and 'Offer Help') in the main navigation 

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#17]
@redaranj In the intermediary between mobile and desktop view, the view begins to break and the buttons disappear. Pop them up above or below so there is enough room for them. 
When you're available, let's just on a call to discuss.

**Comment by tiffrobo** [comment]
@redaranj The buttons are still disappearing when you change the browser size. They are no longer even staking, just disappearing completely.

**Comment by redaranj** [comment]
@tiffrobo @levjoy There's a fix for this in the develop branch now.

**Comment by tiffrobo** [comment]
Thanks @redaranj We will push it!

**Comment by tiffrobo** [comment]
@redaranj Get Help and Offer Help buttons do not appear in the collapsed menu. Can we make sure they do please?

**Comment by redaranj** [comment]
@tiffrobo @levjoy A fix for the missing Get Help & Offer Help buttons in the mobile menu is in the develop branch.

**Comment by tiffrobo** [comment]
We will push! Thank you!

**Comment by tiffrobo** [comment]
@redaranj the buttons are in for mobile (both iOS and Android) and the 'X' works. The buttons are in and the 'X' is working on safari. 
- However, the buttons are not in and the 'X' doesn't work for Chrome. Can we fix this?

- I am making a new ticket for firefox browser because it is definitely messed up!

**Comment by tiffrobo** [comment]
Hey all, it was my chrome browser! I needed to clear my cache. It looks and functions great! Thanks @redaranj and @abeluck
