### ISSUE TITLE
add twitter to the footer

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#20]
add twitter icon and hook to the footer

**Comment by tiffrobo** [comment]
@redaranj We'd like to add the twitter icon and hook to the DSX twitter account at the bottom of the homepage. There is a small copy change right above the twitter icon too.  I've attached a mockup and the files needed. Let me know if you have any questions.
![twitter_icon](https://user-images.githubusercontent.com/30634981/45956606-9b0d9580-bfd8-11e8-8c06-7e769978ac27.png)
![twitter_iconx2](https://user-images.githubusercontent.com/30634981/45956612-9cd75900-bfd8-11e8-946d-128c3ee33c59.png)
![dsx_home_v5-twitterfooter](https://user-images.githubusercontent.com/30634981/45956602-98ab3b80-bfd8-11e8-9765-d14ec2d41274.jpg)

**Comment by redaranj** [comment]
@tiffrobo Twitter footer changes are in the develop branch.

**Comment by tiffrobo** [comment]
Thanks!

**Comment by tiffrobo** [comment]
Everything's in! Sorry, all. I needed to clear my cache
