### ISSUE TITLE
'X' doesn't work to close out of the menu

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#22]
In mobile and tablet view when you click on the menu the 'X' in the top right doesn't work. Won't close out of the window. 
Please fix @redaranj 
Here's a photo 
<img width="743" alt="screen shot 2018-09-10 at 5 29 27 pm" src="https://user-images.githubusercontent.com/30634981/45327977-618c5300-b51f-11e8-8662-835988995bd6.png">

**Comment by redaranj** [comment]
@tiffrobo @levjoy A fix for the mobile menu close button is in the develop branch.

**Comment by tiffrobo** [comment]
Thanks

**Comment by tiffrobo** [comment]
I'm closing this ticket. See ticket #17 for updates
