### ISSUE TITLE
Add updated Security Positive logo to home page 

### ISSUE THREAD

**Issue by levjoy** [digital-security-exchange/exchange-new#24]
![secpos_long](https://user-images.githubusercontent.com/122013/45919758-81e5d700-be68-11e8-991b-6858c00f7b31.png)

**Comment by tiffrobo** [comment]
@redaranj Under the provider's section on the homepage can you replace the current Security+ logo with this new one?

**Comment by levjoy** [comment]
Thanks. Tiffany, do you think we should monochrome-ize it?

On 26 Sep 2018, at 8:36, Darren Clarke wrote:

> @tiffrobo Added it in the develop branch. It looks a little out of 
> place with others which are all the same monochrome bluish-black.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/digital-security-exchange/exchange-new/issues/24#issuecomment-424632881




--
Josh Levy
Technology Director
Center for Digital Resilience
https://digiresilience.org

PGP Fingerprint: B56A D510 3142 2364 69C7 3961 A0A3 67A5 84C9 F275

**Comment by tiffrobo** [comment]
ah yes! We should monochorome-ize it. @redaranj I'll send over the blue png

**Comment by tiffrobo** [comment]
@redaranj here's the mono logo. Please replace the existing security+ with this one! Thanks
![security](https://user-images.githubusercontent.com/30634981/46086124-11430100-c16d-11e8-940c-f3a3fafd9d78.png)

**Comment by redaranj** [comment]
@tiffrobo OK, updated logo is in develop.

**Comment by tiffrobo** [comment]
thanks. @levjoy can you close this ticket please.
