### ISSUE TITLE
Update copy to newsletter signup page

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#31]
@redaranj We need to update the language on the [newsletter signup page](https://digitalsecurityexchange.org/signup/). Here is what we need it to say:

Sign up to our list below to receive DSX's monthly newsletter featuring digital security news and reports, updates about recent threats, and tips for how to keep yourself safe online.

Do you have time to update this copy?

**Comment by redaranj** [comment]
@tiffrobo I can do it today, but do you want to keep the line "We will not include any sensitive information in this newsletter" at the end?

**Comment by tiffrobo** [comment]
@redaranj good question. We will change the last line to this: 
"We use Mailchimp to manage our email lists. Only your email address will be stored. For more, see [Mailchimp's privacy policy](https://mailchimp.com/legal/privacy/)."

**Comment by redaranj** [comment]
@tiffrobo OK, the change is in 'develop'.

**Comment by tiffrobo** [comment]
Wonderful! Thank you!
