### ISSUE TITLE
new 'Get Help' page

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#33]
@redaranj Here is the mockup for the new Get Help page on DSX. The copy has been changed and the form will now be a separate page.

![dsx_ get-help_15](https://user-images.githubusercontent.com/30634981/52296341-b8b61880-2943-11e9-96db-3a4885f1675e.jpg)
[icons-2.zip](https://github.com/digital-security-exchange/exchange-new/files/2833390/icons-2.zip)

**Comment by redaranj** [comment]
@tiffrobo The updated 'request-assistance / 'request-assistance-form' pages are on the branch 'feature/update-get-help' for your review.

**Comment by tiffrobo** [comment]
It looks great Darren! 
A few things:

- [ ] Can you change the email to read help@dsx.us 

- [ ] Also in the footer, update the email to read help@dsx.us

- [ ] Make Signal open in a new window

- [ ] Make the Request Help Form open in a new window

Sorry I didn't catch these before.

**Comment by abeluck** [comment]
I can do these.. I'm in the code right now updating the domain.

@tiffrobo  should the email be updated just on the request assistance page? Or should it be updated all over the site?

**Comment by tiffrobo** [comment]
@abeluck thank you! The footer needs to be updated all over the site.

**Comment by abeluck** [comment]
> @abeluck thank you! The footer needs to be updated all over the site.

What about all the blog posts and other instances?

I see `info@digitalsecurityexchange.org` and `used@digitalsecurityexchange.org` used in dozens of places. Should I update all those to `help@dsx.us`?

**Comment by tiffrobo** [comment]
Within the footer, the 'middle section' seems to be responding strange when I make the window size smaller. 
<img width="1016" alt="screen shot 2019-02-20 at 12 05 23 pm" src="https://user-images.githubusercontent.com/30634981/53113954-5a269800-3508-11e9-9855-68e6de8438be.png">
<img width="1078" alt="screen shot 2019-02-20 at 12 06 03 pm" src="https://user-images.githubusercontent.com/30634981/53113955-5a269800-3508-11e9-8f2a-64374f1e6763.png">

- [ ] Notice the Twitter Icon
- [ ] PGP Key
- [ ] 'Conduct'

**Comment by tiffrobo** [comment]
One more change...Can we update the copy on the 'Get Help' page under the email icon to say,

- [ ] "Get in touch via email."
