### ISSUE TITLE
Add Ingrid Skoog to DSX About Page

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#35]
@redaranj We need to add Ingrid Skoog to the DSX About page under "Who We Are"
You should be able to grab all the assets from the CDR repo/website. 
- [x] Bio
- [x] Avatar
- [x] Her title will say "CDR Security Director"

Our order should be Josh, Ingrid, Tiffany, followed by the Advisory Committee. 
Thanks!

**Comment by redaranj** [comment]
@tiffrobo The style of the avatar is somewhat different between DSX & CDR. DSX needs a light gray circle behind and it also looks like the eyes are deemphasized.

**Comment by tiffrobo** [comment]
Oh good call! 
Josh's avatar needs to be updated too! We updated his CDR one, but not DSX. 
I will get a DSX-like Avatar for Ingrid.

**Comment by redaranj** [comment]
@tiffrobo The Ingrid / profile image changes are on the 'develop' branch. Let's talk at the meeting today about deploying it to staging - I might be doing it this time.

**Comment by tiffrobo** [comment]
Sounds good Darren! Thanks!
