### ISSUE TITLE
Updates to the DSX 'get help' page

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#37]
Hello @redaranj We have a few updates to the design of the DSX get help page. 

Here is the updated design and assets. Please let me know if you need anything else.

- [x] under the form, decrease the security level 

- [x] change the security level color for the web form

- [x] open the lock for web form

- [x] decrease the security level for email 

- [x] change the security level color for email

[Get-Help-Assets.zip](https://github.com/digital-security-exchange/exchange-new/files/3085914/Get-Help-Assets.zip)
![DSX_ Get-Help_v2](https://user-images.githubusercontent.com/30634981/56227511-45174280-603b-11e9-9d36-1dffa0543405.jpg)

**Comment by tiffrobo** [comment]
I saw the new push! One small-ish thing.....The Form and Email colors were meant to be switched! 
We need this 
<img width="317" alt="Screen Shot 2019-04-23 at 11 06 30 AM" src="https://user-images.githubusercontent.com/30634981/56597372-f2e49d00-65b7-11e9-8616-1d7ef3d95962.png">


We currently have this
<img width="571" alt="Screen Shot 2019-04-23 at 11 06 43 AM" src="https://user-images.githubusercontent.com/30634981/56597394-fa0bab00-65b7-11e9-8585-8754d5c3760e.png">

@redaranj Can we make this update?

**Comment by redaranj** [comment]
@tiffrobo @abeluck OK, image colors are updated on 'develop' now.

**Comment by tiffrobo** [comment]
Thank you!!

**Comment by tiffrobo** [comment]
Thank you all!
