### ISSUE TITLE
Enable javascript UI element 

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#38]
@redaranj or @abeluck  I'm not sure who is best suited for this, but we need a component/UI element for users who have javascript turned off, to 'enable javascript to view this page.' 
I think we only need this element for the 'Offer Help form' and 'Get Help form' (which submits to Zammad). 

Do you need a design for this?

**Comment by redaranj** [comment]
@tiffrobo @abeluck I can take care of this while I'm making the other changes to the form. Probably don't need a design – I'll just set it in one of the existing fonts on that page.

**Comment by tiffrobo** [comment]
@redaranj  Thank you!

**Comment by tiffrobo** [comment]
Looks to be working! Thanks
